### ISSUE TITLE
Chained CSS selectors get over-applied

### ISSUE THREAD

**Issue by craiglabenz** [rennat/pynliner#35]
CSS of the form `selector, selector { style-rules; }` do not seem to get applied correctly. See the example below where both `<p>` tags render orange, instead of just the one living inside the appropriate wrapper class.

This HTML:

``` html
<div class="orange-wrapper">
    <p>Orange.</p>
</div>
<div>
    <p>Black.</p>
</div>
```

Mixed with this CSS:

``` css
.orange-wrapper p, .super-orange-wrapper p {
    color:orange;
}
```

Results in this inlined HTML:

``` html
<div class="orange-wrapper">
    <p style="color: orange">Orange.</p>
</div>
<div>
    <p style="color: orange">Black.</p>
</div>
```
